export * as HomeSVG from './home-svg';
export * as WikiSVG from './wiki-svg';
export * as ProfileSVG from './profile-svg';
export * as SearchSVG from './search-svg';
export * as LogoutSVG from './logout-svg';
export * as StarSVG from './star-svg';
export * as ConfigSVG from './configuration-svg';
export * as TrashSVG from './trash-svg';
export * as ArrowBackSVG from './arrow-back-svg';
